#@data/values
---
tld_domain: tmc.h2o-4-12022.h2o.vmware.com     #! enter the domain. a subdomain like "tmc." is recommended as in the example.
harbor:
  fqdn: harbor.tmc.h2o-4-12022.h2o.vmware.com  #! enter the Harbor FQDN. No "http"/"https" needed.
  user: admin                                  #! enter the Harbor username
  pass: VMware1!                               #! enter the Harbor password
  deploy:
    enabled: true                              #! true/false . enable this for automatic harbor deployment in VM.
    datastore_name: vsanDatastore              #! datastore name for content library and harbor
    port_group_name: management-pg             #! name of the portgroup/network where harbor will run
    ip: 10.220.68.27                           #! ip address for harbor
    netmask: 255.255.255.224                   #! netmask for harbor
    gateway: 10.220.68.30                      #! gateway for harbor
    dns: 10.220.136.2                          #! dns server for harbor
    dns_domain: h2o-4-12022.h2o.vmware.com     #! search domain for harbor
    ca_crt: |-                                 #! Paste tmc-ca.crt / Or, paste Root CA cert of Harbor FQDN
      -----BEGIN CERTIFICATE-----
      MIIFrTCCA5WgAwIBAgIJAKWUQptOQgoxMA0GCSqGSIb3DQEBCwUAMIGEMQswCQYD
      VQQGEwJUUjERMA8GA1UECAwISXN0YW5idWwxETAPBgNVBAcMCElzdGFuYnVsMRcw
      ...
      /2A0B00jNxmc6u7hZ6tVvZhaYMuVzFdTlcLMCuO9hC8DoqX/SP/o3MFkN/cswA0c
      A68ATA67uSZlkBcUVFMT8mNzIahK82WwHP0/cG+bAMypwidUOzJ+WvHaix4AtcIZ
      aNWuv2Wcc5ebQWexaw0frvY=
      -----END CERTIFICATE-----
    server_crt: |-                             #! Paste server-app.crt / Or, paste the cert of Harbor FQDN
      -----BEGIN CERTIFICATE-----
      MIIGkzCCBHugAwIBAgIJAKAAXoMbOhe4MA0GCSqGSIb3DQEBDQUAMIGEMQswCQYD
      ...
      At4Ns5/A4w==
      -----END CERTIFICATE-----
    server_key: |-                             #! Paste server-app.key / Or, paste the key of Harbor FQDN
      -----BEGIN PRIVATE KEY-----
      MIIJRAIBADANBgkqhkiG9w0BAQEFAASCCS4wggkqAgEAAoICAQDS5LsQ41uNtcrw
      ...
      gDULG8v/nx9ThDmGox1FesAQ3s9pNrG/
      -----END PRIVATE KEY-----
std_repo: v2.2.0_update.2                      #! enter the tanzu package version. You do not need to change that with current release.
tmc_repo: 1.0.1                                #! enter the tmc package version.
loadbalancer_ip: 10.220.67.102                 #! define and enter an empty loadbalancer ip address from the loadbalancer subnet.
auth:
  ldap:
    enabled: true                              #! true or false . if you want openldap to be configured automatically, enable this.
  oidc:
    enabled: false                             #! true or false . if you want to use OIDC identity provider, enable this.
    issuerURL: https://asd                     #! enter OIDC url
    clientID: asd                              #! enter OIDC clientID
    clientSecret: asd                          #! enter OIDC clientSecret
shared_cluster:
  namespace: platform                          #! the tmc cluster that is going to be provisioned, will be in this vSphere namespace
  k8s_version: v1.23.8---vmware.3-tkg.1        #! the tmc cluster that is going to be provisioned, will use this k8s version
  storage: tanzu                               #! the tmc cluster that is going to be provisioned, will use this storage
wcp:
  ip: 10.220.65.100                            #! supervisor ip
  user: administrator@vsphere.local            #! username
  password: VMware1!                           #! password
vcenter:
  fqdn: vc01.h2o-4-12022.h2o.vmware.com        #! vCenter FQDN or IP. No "http"/"https" needed.
trustedCAs:                                    #! Certificate section
  #! Paste tmc-ca.crt / Example: CA Cert for *.tmc.corp.com / This will be be Root CA for TMC-SM's domain.
  tmc_ca: |-
    -----BEGIN CERTIFICATE-----
    MIIFrTCCA5WgAwIBAgIJAKWUQptOQgoxMA0GCSqGSIb3DQEBCwUAMIGEMQswCQYD
    VQQGEwJUUjERMA8GA1UECAwISXN0YW5idWwxETAPBgNVBAcMCElzdGFuYnVsMRcw
    ...
    /2A0B00jNxmc6u7hZ6tVvZhaYMuVzFdTlcLMCuO9hC8DoqX/SP/o3MFkN/cswA0c
    A68ATA67uSZlkBcUVFMT8mNzIahK82WwHP0/cG+bAMypwidUOzJ+WvHaix4AtcIZ
    aNWuv2Wcc5ebQWexaw0frvY=
    -----END CERTIFICATE-----
  #! Paste tmc-ca-no-pass.key / Example: CA Key for *.tmc.corp.com / If you're using your own certs, add your un-encrypted Root CA Cert Key.
  tmc_key: |-
    -----BEGIN RSA PRIVATE KEY-----
    MIIJKgIBAAKCAgEA7xcuX9hnmbUoFKsdvO2XnEP+M42dksAWOJso/x78xulDYQQs
    ...
    MlgzPM32OSjhyErlj1aOFPRIJXGg3cPRWCoHV51f2lzUXdLkJIWcwQhWXTealw==
    -----END RSA PRIVATE KEY-----
  #! Paste other ca.crt files / Example: CA Cert for *.tap.corp.com / If you don't have other CAs remove the values from line 54 to 61.
  other_ca: |-
    -----BEGIN CERTIFICATE-----
    MIIFrTCCA5WgAwIBAgIJAIjU55dYs8ORMA0GCSqGSIb3DQEBCwUAMIGEMQswCQYD
    VQQGEwJUUjERMA8GA1UECAwISXN0YW5idWwxETAPBgNVBAcMCElzdGFuYnVsMRcw
    ...
    wpzYazH1Y/xwH7lrZ7zL8WDtYSNCtNKlpIpOmT7bRGHHabB4CkfQmZgIlQhDXs6r
    bhsM31ea8EuDv9orDHfHPTo=
    -----END CERTIFICATE-----